[package]
authors = ["Sean Bowe <sean@z.cash>", "Alex Vlasov <alex.m.vlasov@gmail.com>"]
description = "Cryptographic library for Zcash Sapling with more content"
documentation = "https://github.com/matter-labs/sapling-crypto"
homepage = "https://github.com/matter-labs/sapling-crypto"
license = "MIT/Apache-2.0"
name = "sapling-crypto_ce"
repository = "https://github.com/matter-labs/sapling-crypto"
version = "0.0.4"

[lib]
crate-type = ["lib", "staticlib"]

[features]
default = ["multicore"]
multicore = ["bellman_ce/multicore"]
 
[dependencies]
rand = "0.4"
digest = "0.7"
byteorder = "1"
serde = "1.0.80"
serde_derive = "1.0.80"
tiny-keccak = "1.4.2"

#bellman_ce = { path = "../bellman"}
bellman_ce = { version = "0.3.0", default-features = false}

[dependencies.blake2-rfc]
path = "./src/dependencies/blake2-rfc/"
#git = "https://github.com/gtank/blake2-rfc"
#rev = "7a5b5fc99ae483a0043db7547fb79a6fa44b88a9"

[dev-dependencies]
hex-literal = "0.1"
rust-crypto = "0.2"
